CREATE TABLE [dbo].[employee_details] (
    [Username]                              INT             NULL,
    [PositionID]                            NVARCHAR (1000) NULL,
    [EmployeeStatus]                        NVARCHAR (MAX)  NULL,
    [FirstName]                             NVARCHAR (MAX)  NULL,
    [MiddleName]                            NVARCHAR (MAX)  NULL,
    [LastName]                              NVARCHAR (MAX)  NULL,
    [BusinessEmailInformationEmailAddress]  NVARCHAR (MAX)  NULL,
    [CTC_Currency]                          NVARCHAR (MAX)  NULL,
    [FIXPAY_Amount]                         INT             NULL,
    [RETIRALS_Amount]                       INT             NULL,
    [VARPAY_Amount]                         INT             NULL,
    [OTE_Amount]                            INT             NULL,
    [AnnualFringe_Amount]                   INT             NULL,
    [CTC_Amount]                            NVARCHAR (100)  NULL,
    [Job_Code]                              NVARCHAR (MAX)  NULL,
    [BU_SSUDescription]                     NVARCHAR (MAX)  NULL,
    [LOB_SegmentDescription]                NVARCHAR (MAX)  NULL,
    [VerticalDescription]                   NVARCHAR (MAX)  NULL,
    [SubVerticalDescription]                NVARCHAR (MAX)  NULL,
    [EntityDescription]                     NVARCHAR (MAX)  NULL,
    [ReportingManagerUserSysID]             NVARCHAR (MAX)  NULL,
    [ReportingManager]                      NVARCHAR (MAX)  NULL,
    [CostCenterDescription]                 NVARCHAR (MAX)  NULL,
    [InternationalRegion]                   NVARCHAR (MAX)  NULL,
    [FacilityCountry]                       NVARCHAR (MAX)  NULL,
    [FacilityDescription]                   NVARCHAR (MAX)  NULL,
    [JobLevel]                              NVARCHAR (MAX)  NULL,
    [BandSubBandDescription]                NVARCHAR (MAX)  NULL,
    [Title]                                 NVARCHAR (MAX)  NULL,
    [EmploymentDetailsTataGroupJoiningDate] NVARCHAR (MAX)  NULL,
    [EmploymentDetailsHireDate]             DATE            NULL,
    [EmploymentDetailsLastWorkingDate]      NVARCHAR (MAX)  NULL,
    [EmploymentDetailsTerminationDate]      DATE            NULL,
    [Event]                                 NVARCHAR (MAX)  NULL,
    [EventReason]                           NVARCHAR (MAX)  NULL,
    [EmployeeType]                          NVARCHAR (MAX)  NULL,
    [EmployeeClass]                         NVARCHAR (MAX)  NULL,
    [JobFamilyDescription]                  NVARCHAR (MAX)  NULL,
    [InternalSpecializationName]            NVARCHAR (MAX)  NULL,
    [JobCode]                               NVARCHAR (MAX)  NULL,
    [JobCodeDescription]                    NVARCHAR (MAX)  NULL,
    [VariablePayPlanType]                   NVARCHAR (MAX)  NULL,
    [Gender]                                NVARCHAR (MAX)  NULL,
    [AccountID]                             NVARCHAR (MAX)  NULL,
    [BUSSUCode]                             NVARCHAR (MAX)  NULL,
    [LOBSegmentCode]                        NVARCHAR (MAX)  NULL,
    [VerticalCode]                          NVARCHAR (MAX)  NULL,
    [SubVerticalCode]                       NVARCHAR (MAX)  NULL,
    [CostCenterCode]                        NVARCHAR (MAX)  NULL,
    [Name]                                  NVARCHAR (MAX)  NULL,
    [ConfirmationDate]                      DATE            NULL,
    [EntityCode]                            NVARCHAR (MAX)  NULL,
    [JobCodeJobCode]                        NVARCHAR (MAX)  NULL,
    [DateOfBirth]                           DATE            NULL,
    [BUSSUGMCMember]                        NVARCHAR (MAX)  NULL,
    [BandSubBandBandSubBandID]              NVARCHAR (MAX)  NULL,
    [Designation]                           NVARCHAR (MAX)  NULL,
    [LastPromotionDate]                     DATE            NULL,
    [BUHRSPOCJobRelationshipsUserID]        NVARCHAR (MAX)  NULL,
    [BUHRSPOCJobRelationshipsName]          NVARCHAR (MAX)  NULL,
    [REGIONALHRJobRelationshipsUserID]      NVARCHAR (MAX)  NULL,
    [REGIONALHRJobRelationshipsName]        NVARCHAR (MAX)  NULL,
    [Active_Month_Identifier]               NVARCHAR (MAX)  NULL
);

